# .github/workflows/perf-smoke.yml
name: perf-smoke
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  perf:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      # Install LLVM/Clang if your build needs bindgen (fixes clang-sys errors)
      - name: Install LLVM/Clang
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-17-dev libclang-17-dev clang-17 pkg-config
          echo "LLVM_CONFIG_PATH=/usr/lib/llvm-17/bin/llvm-config" >> $GITHUB_ENV
          echo "LIBCLANG_PATH=/usr/lib/llvm-17/lib" >> $GITHUB_ENV

      - name: Install k6
        run: |
          curl -sSL https://github.com/grafana/k6/releases/download/v0.49.0/k6-v0.49.0-linux-amd64.tar.gz \
          | tar xz
          echo "$PWD/k6-v0.49.0-linux-amd64" >> $GITHUB_PATH

      - name: Run perf smoke
        id: k6
        run: |
          make perf-smoke
          cat ./bench/perf/perf_smoke.json

      - name: Upload perf artifact
        uses: actions/upload-artifact@v4
        with:
          name: perf-smoke
          path: ./bench/perf/perf_smoke.json

      - name: Teardown
        if: always()
        run: kill $(cat /tmp/v1.pid) $(cat /tmp/v2.pid) $(cat /tmp/c.pid) || true
