# .github/workflows/perf-smoke.yml
name: perf-smoke
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  perf:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Install pre-built RocksDB
        run: |
          sudo apt-get update
          sudo apt-get install -y librocksdb-dev pkg-config
          echo "ROCKSDB_LIB_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
          echo "ROCKSDB_STATIC=0" >> $GITHUB_ENV
          echo "ROCKSDB_COMPILE=0" >> $GITHUB_ENV

      - name: Install k6
        run: |
          curl -sSL https://github.com/grafana/k6/releases/download/v0.49.0/k6-v0.49.0-linux-amd64.tar.gz \
          | tar xz
          echo "$PWD/k6-v0.49.0-linux-amd64" >> $GITHUB_PATH

      - name: Run perf smoke
        id: k6
        run: |
          make perf-smoke
          cat perf_smoke.json

      - name: Upload perf artifact
        uses: actions/upload-artifact@v4
        with:
          name: perf-smoke
          path: perf_smoke.json

      - name: Teardown
        if: always()
        run: kill $(cat /tmp/v1.pid) $(cat /tmp/v2.pid) $(cat /tmp/c.pid) || true
